services:
  secretwireguard:
    build:
      context: ../image
    container_name: secretwireguard-server
    env_file:
      - ./.env
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules:ro
    restart: unless-stopped